### ISSUE TITLE
TODO for stable.

### ISSUE THREAD

**Issue by yavorsky** [hellyeahllc/exim#16]
* [x] New Router, using actions. Current router is 5000+ lines.
* [x] Try-Cath on `will[Action]`. Catch will run `didNot[Action]` with error's argument.
* [x] Remove bluebird dependency.
