### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by paulmillr** [hellyeahllc/exim#6]
* [x] Remove fluxy-related stuff, rename to exim (but preserve copyright). Everything in the  After this is done, we should rewrite the implementation.
* [x] Reconsider constants
* [x] Fluxy-router — or make our own ?
* [ ] Some basic guidance for apps, structure
* [x] Docs
